index:
    path: /
    controller: App\Controller\DefaultController::index

category_view:
    path: /category/{slug}
    requirements:
        slug: '^[A-Za-z0-9-_]+$'
    controller: App\Controller\CategoryController::view
